-- 코드를 입력하세요
-- SELECT  p.PRODUCT_CODE, PRICE*o.SALES_AMOUNT SALES, o.SALES_AMOUNT

SELECT PRODUCT_CODE, PRICE * SUM_AMOUNT SALES
FROM PRODUCT p
JOIN
    (SELECT
        PRODUCT_ID,
        sum(SALES_AMOUNT)as SUM_AMOUNT
    from OFFLINE_SALE
    group by PRODUCT_ID) o on (p.PRODUCT_ID = o.PRODUCT_ID)
order by SALES desc, PRODUCT_CODE;