-- 코드를 입력하세요
SELECT  CAR_ID, round(avg(datediff(END_DATE, START_DATE)+1), 1) AVERAGE_DURATION
FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
having AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION desc, CAR_ID DESC;

# SELECT  CAR_ID, END_DATE, START_DATE, datediff(END_DATE, START_DATE)
# FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY CAR_ID DESC;